[package]
name = "julia-rs"
version = "0.1.0"
authors = ["Grant Wade <wadegrant52@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
image = "0.23.10"